//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THD.Core.Api.Repository.ReportFiles {
    
    public partial class rptR16 : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "THD.Core.Api.Repository.ReportFiles.rptR16.repx");

            // Controls
            this.TopMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.TopMarginBand>("TopMargin");
            this.BottomMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.BottomMarginBand>("BottomMargin");
            this.Detail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail");
            this.xrRichText6 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText6");
            this.xrCheckBox14 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("xrCheckBox14");
            this.xrCheckBox13 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("xrCheckBox13");
            this.xrLine3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("xrLine3");
            this.xrCheckBox15 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("xrCheckBox15");
            this.xrCheckBox16 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("xrCheckBox16");
            this.xrCheckBox18 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("xrCheckBox18");
            this.xrCheckBox19 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("xrCheckBox19");
            this.xrCheckBox17 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("xrCheckBox17");
            this.xrCheckBox20 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("xrCheckBox20");
            this.xrCheckBox21 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("xrCheckBox21");
            this.xrCheckBox22 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("xrCheckBox22");
            this.xrCheckBox23 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("xrCheckBox23");
            this.xrCheckBox24 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("xrCheckBox24");
            this.xrCheckBox25 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("xrCheckBox25");
            this.xrCheckBox26 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("xrCheckBox26");
            this.xrRichText2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText2");
            this.xrLine1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("xrLine1");
            this.xrRichText5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText5");
            this.xrLine2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("xrLine2");
            this.xrLine4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("xrLine4");
            this.xrLine5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("xrLine5");
            this.xrLine6 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("xrLine6");
            this.xrLine7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("xrLine7");
            this.xrLine8 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("xrLine8");
            this.xrLine9 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("xrLine9");
            this.xrLine10 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("xrLine10");
            this.xrLine11 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("xrLine11");
            this.xrLine12 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("xrLine12");
            this.xrLine14 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("xrLine14");
            this.xrLine13 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("xrLine13");
            this.xrLine15 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("xrLine15");
            this.xrLine16 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("xrLine16");
            this.xrLine17 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("xrLine17");
            this.xrCheckBox1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("xrCheckBox1");
            this.xrLine18 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("xrLine18");
            this.xrCheckBox2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("xrCheckBox2");
            this.xrCheckBox3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("xrCheckBox3");
            this.xrCheckBox4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("xrCheckBox4");
            this.xrLine19 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("xrLine19");
            this.xrCheckBox7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("xrCheckBox7");
            this.xrCheckBox6 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("xrCheckBox6");
            this.xrCheckBox5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("xrCheckBox5");
            this.xrCheckBox9 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("xrCheckBox9");
            this.xrCheckBox8 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("xrCheckBox8");
            this.xrCheckBox11 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("xrCheckBox11");
            this.xrCheckBox10 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("xrCheckBox10");
            this.xrCheckBox12 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("xrCheckBox12");
            this.xrRichText1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("xrRichText1");
            this.label1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label1");

            // Parameters
            this.header_title = reportInitializer.GetParameter("header_title");
        }
        private DevExpress.XtraReports.UI.TopMarginBand TopMargin;
        private DevExpress.XtraReports.UI.BottomMarginBand BottomMargin;
        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.XtraReports.UI.XRRichText xrRichText6;
        private DevExpress.XtraReports.UI.XRCheckBox xrCheckBox14;
        private DevExpress.XtraReports.UI.XRCheckBox xrCheckBox13;
        private DevExpress.XtraReports.UI.XRLine xrLine3;
        private DevExpress.XtraReports.UI.XRCheckBox xrCheckBox15;
        private DevExpress.XtraReports.UI.XRCheckBox xrCheckBox16;
        private DevExpress.XtraReports.UI.XRCheckBox xrCheckBox18;
        private DevExpress.XtraReports.UI.XRCheckBox xrCheckBox19;
        private DevExpress.XtraReports.UI.XRCheckBox xrCheckBox17;
        private DevExpress.XtraReports.UI.XRCheckBox xrCheckBox20;
        private DevExpress.XtraReports.UI.XRCheckBox xrCheckBox21;
        private DevExpress.XtraReports.UI.XRCheckBox xrCheckBox22;
        private DevExpress.XtraReports.UI.XRCheckBox xrCheckBox23;
        private DevExpress.XtraReports.UI.XRCheckBox xrCheckBox24;
        private DevExpress.XtraReports.UI.XRCheckBox xrCheckBox25;
        private DevExpress.XtraReports.UI.XRCheckBox xrCheckBox26;
        private DevExpress.XtraReports.UI.XRRichText xrRichText2;
        private DevExpress.XtraReports.UI.XRLine xrLine1;
        private DevExpress.XtraReports.UI.XRRichText xrRichText5;
        private DevExpress.XtraReports.UI.XRLine xrLine2;
        private DevExpress.XtraReports.UI.XRLine xrLine4;
        private DevExpress.XtraReports.UI.XRLine xrLine5;
        private DevExpress.XtraReports.UI.XRLine xrLine6;
        private DevExpress.XtraReports.UI.XRLine xrLine7;
        private DevExpress.XtraReports.UI.XRLine xrLine8;
        private DevExpress.XtraReports.UI.XRLine xrLine9;
        private DevExpress.XtraReports.UI.XRLine xrLine10;
        private DevExpress.XtraReports.UI.XRLine xrLine11;
        private DevExpress.XtraReports.UI.XRLine xrLine12;
        private DevExpress.XtraReports.UI.XRLine xrLine14;
        private DevExpress.XtraReports.UI.XRLine xrLine13;
        private DevExpress.XtraReports.UI.XRLine xrLine15;
        private DevExpress.XtraReports.UI.XRLine xrLine16;
        private DevExpress.XtraReports.UI.XRLine xrLine17;
        private DevExpress.XtraReports.UI.XRCheckBox xrCheckBox1;
        private DevExpress.XtraReports.UI.XRLine xrLine18;
        private DevExpress.XtraReports.UI.XRCheckBox xrCheckBox2;
        private DevExpress.XtraReports.UI.XRCheckBox xrCheckBox3;
        private DevExpress.XtraReports.UI.XRCheckBox xrCheckBox4;
        private DevExpress.XtraReports.UI.XRLine xrLine19;
        private DevExpress.XtraReports.UI.XRCheckBox xrCheckBox7;
        private DevExpress.XtraReports.UI.XRCheckBox xrCheckBox6;
        private DevExpress.XtraReports.UI.XRCheckBox xrCheckBox5;
        private DevExpress.XtraReports.UI.XRCheckBox xrCheckBox9;
        private DevExpress.XtraReports.UI.XRCheckBox xrCheckBox8;
        private DevExpress.XtraReports.UI.XRCheckBox xrCheckBox11;
        private DevExpress.XtraReports.UI.XRCheckBox xrCheckBox10;
        private DevExpress.XtraReports.UI.XRCheckBox xrCheckBox12;
        private DevExpress.XtraReports.UI.XRRichText xrRichText1;
        private DevExpress.XtraReports.Parameters.Parameter header_title;
        private DevExpress.XtraReports.UI.XRLabel label1;
    }
}
